### ISSUE TITLE
If encoding is specified then the first argument must be a string

### ISSUE THREAD

**Issue by soldiertt** [gkovacs/read-each-line#2]
Hi,

Using : `readEachLine(filePath, "utf8", function(line) {`

I'm facing this issue :

```
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at readEachLine (D:\javadev\prj\node\moneyv2\node_modules\read-each-line\read-each-line.js:78:21)
    at D:\javadev\prj\node\moneyv2\server\src\dist\ctrl\csvfiles.srv.ctrl.js:19:21
    at Array.forEach (native)
    at D:\javadev\prj\node\moneyv2\server\src\dist\ctrl\csvfiles.srv.ctrl.js:13:19
    at FSReqWrap.oncomplete (fs.js:117:15)

```

Maybe related to any dependency update ? I'm using the latest version of node.js/npm

**Comment by soldiertt** [comment]
it should be related to buffer.js api change :
https://nodejs.org/api/buffer.html#buffer_new_buffer_str_encoding
(in node.js 6.2.0)

**Comment by gkovacs** [comment]
I've fixed nodejs compatibility as of the latest version 1.0.6 (just uploaded to npm)
